# Generated by Django 4.1.3 on 2022-12-09 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_wiki_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
